AWSTemplateFormatVersion: '2010-09-09'
Description: Grupolab16_Cuba_Ferrer

Resources:
  VPCSEM16:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  MySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPCSEM16
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: !Select
        - 0
        - !GetAZs ''

  MyInternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPCSEM16
      InternetGatewayId: !Ref MyInternetGateway

  MyRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPCSEM16

  MyRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref MyRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MyInternetGateway

  MySubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref MySubnet
      RouteTableId: !Ref MyRouteTable

  EC2SEM16:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0d00fdd4689a5d575 
      SubnetId: !Ref MySubnet
      SecurityGroupIds:
        - !Ref EC2SEM16SecurityGroup

  EC2SEM16SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPCSEM16 # Asociar el grupo de seguridad a la VPC
      GroupDescription: Enable SSH and S3 access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 # Permitir acceso SSH desde cualquier lugar
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0 # Permitir todo el tráfico TCP saliente
        - IpProtocol: udp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0 # Permitir todo el tráfico UDP saliente
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0 # Permitir todo el tráfico ICMP saliente

  S3SEM16:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sem16-bucket

Outputs:
  VPCId:
    Description: VPC ID
    Value: !Ref VPCSEM16

  SubnetId:
    Description: Subnet ID
    Value: !Ref MySubnet

  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref EC2SEM16

  SecurityGroupId:
    Description: Security Group ID
    Value: !Ref EC2SEM16SecurityGroup

  S3BucketName:
    Description: S3 Bucket Name
    Value: !Ref S3SEM16
